name: create-deployslot.yml - Create deployment slot on new branch creation

on:
  create:
    branches: 
      - 'feature/*'

env:
  AZURE_WEBAPP_NAME: somename
  RESOURCE_GROUP: somegroup

jobs:
  create-deployslot:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
    - name: Did I run?
      run: echo "Why did I run"
